MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
#  TRAIN: ("crag",)
#  TEST: ("crag_val",)
#  TRAIN: ("coco_2017_train",)
#  TEST: ("coco_2017_val",)
#  TRAIN: ("glassp_png_train",)
#  TEST: ("glassp_png_val",)
#  TRAIN: ("glas_png_train",)
#  TEST: ("glas_png_val",)
#  TRAIN: ("glaserode_train",)
#  TEST: ("glaserode_val",)
  TRAIN: ("glas_png_train",)
  TEST: ("glas_png_val",)
#  TRAIN: ("breast_train",)
#  TEST: ("breast_val",)
#  TRAIN: ("glas_aug_train",)
#  TEST: ("glas_aug_val",)
SOLVER:
  IMS_PER_BATCH: 16

  BASE_LR: 0.0001
#  MAX_ITER: 25950
#  STEPS: (23066, 24988)
  MAX_ITER: 8500
  STEPS: (7555, 8185)

  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  #glas:
  IMAGE_SIZE:  513 #512 #768 #800 #768 #1440 #1472 #768 #1024 # 1504 #512 #768 #1024  #960
  #IMAGE_SIZE:  768 #768 #800 #768 #1440 #1472 #768 #1024 # 1504 #512 #768 #1024  #960
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0 #2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj"
TEST:
  EVAL_PERIOD: 346
#  EVAL_PERIOD: 5000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
#  NUM_WORKERS: 4
  NUM_WORKERS: 0
VERSION: 2

#--config-file configs/coco/instance-segmentation/dinat/maskformer2_dinat_large_IN21k_384_bs16_100ep.yaml --num-gpus 1 SOLVER.BASE_LR 0.0001 SOLVER.IMS_PER_BATCH 4 > /home/cvml/Hsuan/Mask2Former-res2_3_4_fgseg/txtRecord/0606aug.txt